// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_vWZjngPONH-eG8uJ6x7eqY71bOcWEQA',
    appId: '1:237618928003:web:c5df5d03488dcc9c897eb6',
    messagingSenderId: '237618928003',
    projectId: 'myrepo-3d965',
    authDomain: 'myrepo-3d965.firebaseapp.com',
    storageBucket: 'myrepo-3d965.appspot.com',
    measurementId: 'G-EDE198Q7WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5mwQrEG9Nic_FkGzRtbms-nswPBpOS38',
    appId: '1:237618928003:android:6b3f6a4414891ae8897eb6',
    messagingSenderId: '237618928003',
    projectId: 'myrepo-3d965',
    storageBucket: 'myrepo-3d965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx10u_ajLpdoTCrWRHHPuEiLsNr4OLIkw',
    appId: '1:237618928003:ios:d2057c7511c2eacf897eb6',
    messagingSenderId: '237618928003',
    projectId: 'myrepo-3d965',
    storageBucket: 'myrepo-3d965.appspot.com',
    iosClientId: '237618928003-kvhg12mt2muos3vdpdakdrh81aahv2s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx10u_ajLpdoTCrWRHHPuEiLsNr4OLIkw',
    appId: '1:237618928003:ios:d2057c7511c2eacf897eb6',
    messagingSenderId: '237618928003',
    projectId: 'myrepo-3d965',
    storageBucket: 'myrepo-3d965.appspot.com',
    iosClientId: '237618928003-kvhg12mt2muos3vdpdakdrh81aahv2s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnflutter',
  );
}
